### ISSUE TITLE
Camera Emulator does not start

### ISSUE THREAD

**Issue by amunchet** [amunchet/security#1]
Camera emulator does not start.

```
[2019-09-10 20:19:17,622] INFO in emulator: serving
cameraemulator_1         | Exception in thread Thread-3:
cameraemulator_1         | Traceback (most recent call last):
cameraemulator_1         |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
cameraemulator_1         |     self.run()
cameraemulator_1         |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
cameraemulator_1         |     self._target(*self._args, **self._kwargs)
cameraemulator_1         |   File "/home/appuser/app/emulator.py", line 47, in gen_serve_upload
cameraemulator_1         |     self.serve(file_path)
cameraemulator_1         |   File "/home/appuser/app/emulator.py", line 29, in serve
cameraemulator_1         |     copyfile(file_path, dest)
cameraemulator_1         |   File "/usr/local/lib/python3.6/shutil.py", line 121, in copyfile
cameraemulator_1         |     with open(dst, 'wb') as fdst:
cameraemulator_1         | FileNotFoundError: [Errno 2] No such file or directory: '/home/appuser/app/generated-image/image.jpg'
```

Also, no cameras are displayed:

![image](https://user-images.githubusercontent.com/30327507/64648431-7f192480-d3e0-11e9-874f-6839b7f6d63c.png)

**Comment by amunchet** [comment]
A possibly related issue is this from backend:

```
displayserverbackend_1   |  * Debug mode: on
displayserverbackend_1   |  * Running on http://0.0.0.0:10001/ (Press CTRL+C to quit)
displayserverbackend_1   |  * Restarting with stat
```
**displayserverbackend_1   | WebSocket transport not available. Install eventlet or gevent and 
gevent-websocket for improved performance.**
```
displayserverbackend_1   |  * Debugger is active!
```

**Comment by marcello-dev** [comment]
This should be fixed with the pull request #3
